"""Generate a synthetic Colonist screenshot fixture for testing the fixture pipeline.

Run once to create tests/fixtures/colonist/synthetic_setup.png + .json.
The image uses the same rendering helpers as test_colonist_cv_bootstrap_opening.py
so it exercises the bootstrap detector without needing a real Colonist session.
"""

from __future__ import annotations

import math
from pathlib import Path

import cv2
import numpy as np

from catan.board.board import Resource
from catan.board.hex_grid import AXIAL_POSITIONS
from catan.colonist_cv.bootstrap import RESOURCE_HSV_PROTOTYPES
from catan.colonist_cv.detector import DefaultPlayerPalette
from catan.colonist_cv.fixture_store import FIXTURE_DIR, FixtureLabel, PieceLabel, save_label, _hex_key
from catan.colonist_cv.schema import PlayerColor


def _hsv_to_rgb(h: float, s: float, v: float) -> tuple[int, int, int]:
    hsv = np.uint8([[[int(round(h)), int(round(s)), int(round(v))]]])
    rgb = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)[0, 0]
    return int(rgb[0]), int(rgb[1]), int(rgb[2])


RESOURCES = {
    (0, 0): Resource.ORE,    (1, 0): Resource.WHEAT,   (0, 1): Resource.WHEAT,
    (-1, 1): Resource.WHEAT, (-1, 0): Resource.SHEEP,  (0, -1): Resource.SHEEP,
    (1, -1): Resource.WOOD,  (2, 0): Resource.WOOD,    (1, 1): Resource.WOOD,
    (0, 2): Resource.SHEEP,  (-1, 2): Resource.WHEAT,  (-2, 2): Resource.ORE,
    (-2, 1): Resource.DESERT,(-2, 0): Resource.ORE,    (-1, -1): Resource.WOOD,
    (0, -2): Resource.BRICK, (1, -2): Resource.SHEEP,  (2, -2): Resource.BRICK,
    (2, -1): Resource.BRICK,
}
NUMBERS = {
    (2, 0): 12, (2, -1): 11, (0, 0): 11, (0, 2): 10, (0, -1): 10,
    (1, 1): 9,  (-1, 0): 9,  (1, -2): 8, (-1, 2): 8, (1, 0): 6,
    (-2, 0): 6, (0, 1): 5,   (0, -2): 5, (2, -2): 4, (-1, 1): 4,
    (1, -1): 3, (-2, 2): 3,  (-1, -1): 2, (-2, 1): None,
}
DESERT_HEX = (-2, 1)

TX, TY, DX, DY = 762.0, 756.0, 145.0, 125.0
WIDTH, HEIGHT = 1800, 1400


def _hex_center(q: int, r: int) -> tuple[float, float]:
    return (TX + DX * (q + 0.5 * r), TY + DY * r)


def _draw_disk(img: np.ndarray, cx: float, cy: float, radius: float, color: tuple[int, int, int]) -> None:
    cv2.circle(img, (int(round(cx)), int(round(cy))), int(round(radius)), color, -1)


def build_image() -> np.ndarray:
    img = np.full((HEIGHT, WIDTH, 3), (58, 116, 179), dtype=np.uint8)

    # Draw hex tiles
    for h in AXIAL_POSITIONS:
        cx, cy = _hex_center(*h)
        rgb = _hsv_to_rgb(*RESOURCE_HSV_PROTOTYPES[RESOURCES[h]])
        cv2.circle(img, (int(round(cx)), int(round(cy))), 92, rgb, -1)

    # Draw number tokens (white squares) on non-desert hexes
    for h in AXIAL_POSITIONS:
        if h == DESERT_HEX:
            continue
        cx, cy = _hex_center(*h)
        x, y = int(round(cx)), int(round(cy))
        cv2.rectangle(img, (x - 27, y - 27), (x + 27, y + 27), (255, 255, 255), -1)

    # Draw a few pieces so piece-detection fixtures have content
    # Red settlement near hex (0,0)
    sx, sy = _hex_center(0, 0)
    sx += 72
    _draw_disk(img, sx, sy, 14, DefaultPlayerPalette[PlayerColor.RED.value])

    # Blue road between two hexes
    ax, ay = _hex_center(1, 0)
    bx, by = _hex_center(1, 1)
    cv2.line(img, (int(ax), int(ay)), (int(bx), int(by)),
             DefaultPlayerPalette[PlayerColor.BLUE.value], 8)

    return img


def build_label() -> FixtureLabel:
    resources_by_hex = {_hex_key(h): RESOURCES[h].value for h in AXIAL_POSITIONS}
    numbers_by_hex = {_hex_key(h): NUMBERS[h] for h in AXIAL_POSITIONS}

    # Exact canonical vertex coordinates for the pieces we drew.
    # Red settlement: rightmost vertex of hex (0,0) at angle 30°.
    red_settlement = [round(math.cos(math.radians(30)), 6),
                      round(math.sin(math.radians(30)), 6)]
    # Blue road: shared edge between hex (1,0) and hex (1,1).
    # Vertices are (sqrt(3), 1.0) and (sqrt(3)*1.5, 0.5).
    road_v1 = [round(math.sqrt(3), 6), 1.0]
    road_v2 = [round(math.sqrt(3) * 1.5, 6), 0.5]

    red_pieces = PieceLabel(color="red", settlements=[red_settlement])
    blue_pieces = PieceLabel(color="blue", roads=[[road_v1, road_v2]])
    orange_pieces = PieceLabel(color="orange")
    green_pieces = PieceLabel(color="green")
    white_pieces = PieceLabel(color="white")

    return FixtureLabel(
        name="synthetic_setup",
        tags=["synthetic", "setup", "1800x1400"],
        resources_by_hex=resources_by_hex,
        numbers_by_hex=numbers_by_hex,
        desert_hex=list(DESERT_HEX),
        pieces=[red_pieces, blue_pieces, orange_pieces, green_pieces, white_pieces],
        robber_hex=list(DESERT_HEX),
        phase="setup",
        current_player_color="red",
        prompt_text="place settlement",
        hand_resources=None,
        resolution=[WIDTH, HEIGHT],
        notes="Synthetic fixture generated by tests/generate_synthetic_fixture.py",
    )


def main() -> None:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    img = build_image()
    label = build_label()

    img_path = FIXTURE_DIR / "synthetic_setup.png"
    label_path = FIXTURE_DIR / "synthetic_setup.json"

    bgr = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    cv2.imwrite(str(img_path), bgr)
    save_label(label, label_path)
    print(f"Wrote {img_path}")
    print(f"Wrote {label_path}")


if __name__ == "__main__":
    main()
